import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  body: {
    flex: 1,
    backgroundColor: "coral",
    // alignItems: "center",
    // justifyContent: "center",
  },
  firstParagraph: { color: "white", fontSize: 30 },
  buttonContainer: {
    flex: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 8,
    borderRadius: 8,
    width: "100%",
    marginVertical: 25,
  },
  buttonContent: {
    backgroundColor: "tomato",
    color: "white",
    fontSize: 20,
    padding: 12,
    width: "80%",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    borderRadius: 8,
  },
  header: {
    justifyContent: "center",
    alignItems: "center",
    color: "white",
    fontSize: 30,
    paddingTop: 10,
  },
  inputContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 8,
  },
  inputField: {
    border: "1px solid #ddde",
    borderRadius: 8,
    width: 300,
    padding: 16,
  },
  notesContainer: { flex: 1, backgroundColor: "white" },
  noteStyle: {
    flexDirection: "row",
    borderBottomColor: "#ddde",
    borderBottomWidth: 1,
    padding: 10,
    marginVertical: 5,
    alignItems: "center",
  },
  deleteIcon: {
    fontWeight: "bold",
    fontSize: 20,
    color: "red",
    marginRight: 8,
  },
});
